### ISSUE TITLE
Anyway to run a 800x480 HDMI display?

### ISSUE THREAD

**Issue by Virgilius1995** [Owersun/linux-amlogic#1]
I've gotten myself a Waveshare 4" HDMI display 
https://www.waveshare.com/wiki/4inch_HDMI_LCD

Is there any way to output to this display?

Notes
The output for EDID is 
![new bitmap image 2](https://user-images.githubusercontent.com/32931869/44912199-b531bc00-ad29-11e8-9275-3a841e571dcc.png)

Searching for a compatible modeline I've found the following

Modeline "480x800" 12.43 480 512 552 584 800 818 822 841
Modeline "800x480" 11.46 800 832 872 904 480 491 493 505

Through fbset I can set to either these resolutions but nothing shows up on the display
And when adding the following to my fb.modes

mode "800x480-60"
geometry 800 480 800 480 32 
timings 33805 96 24 10 3 72 7 
endmode

I get the following error
"FBIOPUT Invalid argument"

I've posted on Lover-pi forum so I apologize for repeating myself but since you did a lot of the development work for the linux kernel used I thought you might have an idea of what I can do.

**Comment by Owersun** [comment]
I'm honestly not sure about your situation. The kernel here is the one that AML provides in their buildroot, plus few additions for smooth video playback related to hardware decoding.
It should work with monitors and panels the same way default AML provided kernel should. So you better ask this question on any AML board specific forums, where people are familiar with how kernel handles small resolution panels.

**Comment by Virgilius1995** [comment]
Thanks I appreciate the reply.
My search continues(;
